services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-darklife}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    env_file: ../.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    env_file: ../.env
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  renderer:
    build:
      context: ..
      dockerfile: services/renderer/Dockerfile
    env_file: ../.env
    volumes:
      - ../output:/output
      - ../content:/content
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy

  uploader:
    build:
      context: ..
      dockerfile: services/uploader/Dockerfile
    env_file: ../.env
    volumes:
      - ../output:/output
      - ../secrets:/secrets:ro
    depends_on:
      api:
        condition: service_healthy

  reddit_ingestor:
    build:
      context: ..
      dockerfile: services/reddit_ingestor/Dockerfile
    env_file: ../.env
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
    profiles:
      - ops

volumes:
  postgres_data:
  redis_data:
