name: CI

on:
  push:
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter web lint
      - run: pnpm --filter web typecheck
      - run: pnpm --filter web test
      - run: pnpm exec playwright install --with-deps
      - run: pnpm --filter web e2e
      - run: pnpm --filter web build
      - name: Check for leaked admin secrets
        run: "! grep -R --binary-files=text 'ADMIN_API_TOKEN\|ELEVENLABS_API_KEY\|API_AUTH_TOKEN' apps/web/.next"
      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install . pytest httpx
      - name: Run tests
        run: |
          API_AUTH_TOKEN=sekrit ELEVENLABS_API_KEY=apikey pytest -q | tee pytest.log
      - name: Ensure secrets not logged
        run: "! grep -R 'sekrit\|apikey' pytest.log"
