name: Renderer Smoke Test

on:
  pull_request:
    paths:
      - 'video_renderer/**'
      - 'services/renderer/**'
      - 'tests/renderer/**'
      - '.github/workflows/renderer-smoke.yml'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install Python dependencies
        run: pip install . pytest
      - name: Run renderer smoke test
        run: pytest tests/renderer/test_smoke_render.py -q
